### ISSUE TITLE
Scrum Report 2023-07-30

### ISSUE THREAD

**Issue by Ning114** [leoxyu/455-project#97]
Describe (for the project):

    csid:

    (1) what you’ve worked on in the previous two weeks,

    (2) what you’ll be working on in the next two weeks, and

    (3) where you might have gotten stuck during the last two weeks.

These should be quite short (a sentence for each of the three items above).

**Comment by Ning114** [comment]
csid: c9x2b

(1) what you’ve worked on in the previous two weeks,

Getting the playlists to correctly load into the currentPlaylistPage and making sure it syncs with the player.

(2) what you’ll be working on in the next two weeks, and

Wrapping up the currentPlaylistPage by:
- polishing UI for currentPlaylistPage
- adding drop-down menu to remove song from playlist or add it to another playlist, etc.
- checking to see what other simple functionality can be implemented to improve the page before the deadline

(3) where you might have gotten stuck during the last two weeks.

We didn't standardize the playlist and track formats ahead of time, and even if we did it changed many times (adding and removing aspects) as we worked on the page. This caused a lot of headaches come time for merging into main, and I had to 1v1 git for 2 days until I got it to merge properly

**Comment by leoxyu** [comment]
csid: z5z2b

(1) what you’ve worked on in the previous two weeks,
making sure importing songs from youtube is functioning as expected

(2) what you’ll be working on in the next two weeks, and
finishing song page and wrapping up bugs

(3) where you might have gotten stuck during the last two weeks.
deploying the app was a bit of a headache due to it being a SPA

**Comment by AlexZhou876** [comment]
csid: n4z2b

(1) what you’ve worked on in the previous two weeks,
- mongo schema changes to facilitate playlist page
- cursor based pagination and sort, filter, shallow/deep setting for GET playlists
- GET single playlist endpoint and songs REST endpoints
- supported other team members in testing, debugging, reviewing PRs

(2) what you’ll be working on in the next two weeks, and
- helping finalize UI/UX, fixing bugs
- finishing infinite scroll for playlists
- UI success/fail toasts

(3) where you might have gotten stuck during the last two weeks.
- various mongo related challenges

**Comment by wgervasio** [comment]
csid: s0m3b

(1) what you’ve worked on in the previous two weeks,
youtube searching. pagination for youtube and spotify. documenting api changes. logo creation, favicon creation.

(2) what you’ll be working on in the next two weeks, and
fixing ui for search page. adding autocomplete. adding single songs, playlists, albums pages from search. integrating pagination into ui. ML model for recommender.

(3) where you might have gotten stuck during the last two weeks.
api's for youtube 3rd party all had problems and there are also ip blocking issues. managed to resolve by forking a PR version of the repos and using a separate package for playlists.

**Comment by moseshsu01** [comment]
csid: t8v2b

(1) what you’ve worked on in the previous two weeks,
Using the authorID/user id properly to separate playlists between users, fix youtube videos sending data to player and storage, search page options ui fixes, worked a little on deployment to render

(2) what you’ll be working on in the next two weeks, and
bug fixing, testing, maybe working on the liking/favouriting functionality if we have time

(3) where you might have gotten stuck during the last two weeks.
had to wait for certain people to merge their bigger tickets first so as to not fall into merge conflict hell
